// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDESw2bgINzomzrfz99CskXx_X-A8MhiM0',
    appId: '1:13729217659:web:d32c7391e925b6d812f6de',
    messagingSenderId: '13729217659',
    projectId: 'flutter-training-629fe',
    authDomain: 'flutter-training-629fe.firebaseapp.com',
    storageBucket: 'flutter-training-629fe.appspot.com',
    measurementId: 'G-8ZLWLES09G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKa1FN-wmgWNPp5B1GgFCSMD6fHcH90bM',
    appId: '1:13729217659:android:c50f0d2cb5ebc90c12f6de',
    messagingSenderId: '13729217659',
    projectId: 'flutter-training-629fe',
    storageBucket: 'flutter-training-629fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCrBh94j7jBGzxepk1AXQIJGtzKLaEX2U',
    appId: '1:13729217659:ios:3179bf150621664612f6de',
    messagingSenderId: '13729217659',
    projectId: 'flutter-training-629fe',
    storageBucket: 'flutter-training-629fe.appspot.com',
    iosBundleId: 'test.com.example.testsampleproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCrBh94j7jBGzxepk1AXQIJGtzKLaEX2U',
    appId: '1:13729217659:ios:3179bf150621664612f6de',
    messagingSenderId: '13729217659',
    projectId: 'flutter-training-629fe',
    storageBucket: 'flutter-training-629fe.appspot.com',
    iosBundleId: 'test.com.example.testsampleproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDESw2bgINzomzrfz99CskXx_X-A8MhiM0',
    appId: '1:13729217659:web:1a9a3eeda274932712f6de',
    messagingSenderId: '13729217659',
    projectId: 'flutter-training-629fe',
    authDomain: 'flutter-training-629fe.firebaseapp.com',
    storageBucket: 'flutter-training-629fe.appspot.com',
    measurementId: 'G-HMYFG9YS8P',
  );
}

